#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source "${SCRIPT_DIR}/env.sh"

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <command> [args...]"
  exit 2
fi

if [[ ! -e "${SLIME_SIF}" ]]; then
  cat >&2 <<EOF
Missing container image/sandbox:
  ${SLIME_SIF}

Create it with:
  bash ${SCRIPT_DIR}/00_pull_or_load_container.sh
EOF
  exit 1
fi

APPTAINER_BIN="${APPTAINER_BIN:-}"
if [[ -z "${APPTAINER_BIN}" ]]; then
  if command -v apptainer >/dev/null 2>&1; then
    APPTAINER_BIN=apptainer
  elif command -v singularity >/dev/null 2>&1; then
    APPTAINER_BIN=singularity
  else
    echo "Neither apptainer nor singularity is available on PATH." >&2
    exit 1
  fi
fi

mkdir -p \
  "${APPTAINER_CACHEDIR}" \
  "${APPTAINER_TMPDIR}" \
  "${CONTAINER_HOME}" \
  "${TMPDIR}" \
  "${RAY_TMPDIR}"

export APPTAINER_CACHEDIR APPTAINER_TMPDIR

IFS=',' read -r -a BIND_ROOTS <<< "${CONTAINER_BIND_ROOTS}"
APPTAINER_ARGS=(
  exec
  --nv
  --cleanenv
  --ipc
  --writable-tmpfs
  --cwd "${SLIME_REPO_ROOT}"
  --home "${CONTAINER_HOME}:${CONTAINER_HOME_INNER}"
)

for bind_root in "${BIND_ROOTS[@]}"; do
  if [[ -e "${bind_root}" ]]; then
    APPTAINER_ARGS+=(--bind "${bind_root}:${bind_root}")
  fi
done

PASS_ENV=(
  ACCOUNT
  PARTITION
  QOS
  SCRATCH_ROOT
  DATA_ROOT
  MODEL_ROOT
  OUTPUT_ROOT
  HF_HOME
  HF_DATASETS_CACHE
  TRANSFORMERS_CACHE
  VLLM_CACHE_ROOT
  WANDB_MODE
  WANDB_DIR
  TMPDIR
  RAY_TMPDIR
  SLIME_REPO_ROOT
  TILLICUM_EXAMPLE_DIR
  HARP_EXAMPLE_DIR
  STUDENT_HF_REPO
  STUDENT_MODEL_ARGS_SCRIPT
  OPD_WANDB_GROUP_PREFIX
  TEACHER_HF_REPO
  OT3_DATASET
  OT3_SPLIT
  OPENR1_EXPERIMENT_LABEL
  OPENR1_DATASET
  OPENR1_CONFIG
  OPENR1_SPLIT
  OPENR1_REVISION
  OPENR1_DATA_DIR
  OPENR1_SUCCESS_FILE
  MATH500_DATASET
  HARP_SOURCE_CACHE
  HARP_EXISTING_SOURCE
  HARP_JSONL
  HARP_PREP_METADATA
  SOURCE_OPD_1K_JSONL
  SOURCE_OPD_4K_JSONL
  HARP_EVAL_SITE
  HARP_EVAL_INSTALL_SPECS
  QWEN3_ENABLE_THINKING
  QWEN3_IM_END_TOKEN_ID
  QWEN3_ENDOFTEXT_TOKEN_ID
  QWEN3_STOP_TOKEN_IDS
  SFT_SIZE
  OPD_POOL_SIZE
  OPD_TRAIN_SIZE
  OPD_SIZE
  OPD_RUN_LABEL
  DATA_SEED
  DATA_MATH_FIELD
  DATA_MATH_VALUE
  STUDENT_HF_DIR
  TEACHER_HF_DIR
  STUDENT_TORCH_DIST_DIR
  SFT_PARQUET
  OPD_JSONL
  SPLIT_METADATA
  CLEANED_EXPERIMENT_LABEL
  CLEANED_OPD_FIRST_SIZE
  CLEANED_OPD_NEXT_SIZE
  CLEANED_METADATA
  CLEANED_OPD_RESERVE_JSONL
  CLEANED_OPD_1K_JSONL
  CLEANED_OPD_4K_JSONL
  STRICT_EN_EXPERIMENT_LABEL
  STRICT_EN_DATASET_DIR
  STRICT_LANGUAGE_SITE
  STRICT_LANGUAGE_INSTALL_SPEC
  STRICT_EN_SHARD_SIZE
  STRICT_EN_WORKERS
  STRICT_MATH_MAX_SELECTED
  STRICT_OPD_RESERVE_SIZE
  MATH500_JSONL
  MATH500_CONFIG
  MATH500_VAL100_SEED
  MATH500_VAL100_SIZE
  MATH500_VAL100_JSONL
  MATH500_VAL100_CONFIG
  MATH500_VAL100_METADATA
  SFT_SAVE_DIR
  OPD_SAVE_DIR
  SFT_HF_SNAPSHOT_DIR
  OPD_HF_SNAPSHOT_DIR
  SFT_HF_SNAPSHOT_TEMPLATE
  OPD_HF_SNAPSHOT_TEMPLATE
  SFT_FINAL_HF_DIR
  OPD_FINAL_HF_DIR
  SFT_DETAILS_DIR
  OPD_ROLLOUT_LOG_DIR
  TEACHER_LOG_DIR
  EVAL_OUTPUT_DIR
  BASE_EVAL_OUTPUT_DIR
  SFT_EVAL_OUTPUT_DIR
  OPD_EVAL_OUTPUT_DIR
  COMBINED_EVAL_OUTPUT_DIR
  CHECKPOINT_REPORT_DIR
  SLURM_LOG_DIR
  SOURCE_MANIFEST
  SFT_NUM_EPOCH
  SFT_NUM_ROLLOUT
  SFT_FINAL_ROLLOUT_ID
  SFT_MILESTONE_ROLLOUT_IDS
  SFT_ROLLOUT_BATCH_SIZE
  SFT_GLOBAL_BATCH_SIZE
  SFT_MAX_TOKENS_PER_GPU
  SFT_LOG_PROBS_CHUNK_SIZE
  SFT_OPTIMIZER_CPU_OFFLOAD
  SFT_RECOMPUTE_LOSS_FUNCTION
  SFT_ACTOR_GPUS
  SFT_TENSOR_MODEL_PARALLEL_SIZE
  SFT_CONTEXT_PARALLEL_SIZE
  SFT_PIPELINE_MODEL_PARALLEL_SIZE
  SFT_OPTIMIZER_MODE
  SFT_ZERO_STAGE
  SFT_LOSS_MASK_TYPE
  SFT_LOSS_MASK_PREFLIGHT_ENABLED
  SFT_LOSS_MASK_PREFLIGHT_REQUIRE_THINK
  SFT_LOSS_MASK_PREFLIGHT_SAMPLES
  SFT_LR
  SFT_CKPT_FORMAT
  SFT_SAVE_INTERVAL
  OPD_NUM_ROLLOUT
  OPD_FINAL_ROLLOUT_ID
  OPD_EFFECTIVE_TRAIN_SAMPLES
  OPD_MILESTONE_ROLLOUT_IDS
  OPD_ROLLOUT_BATCH_SIZE
  OPD_GLOBAL_BATCH_SIZE
  OPD_N_SAMPLES_PER_PROMPT
  OPD_MAX_RESPONSE_LEN
  OPD_ROLLOUT_MAX_CONTEXT_LEN
  OPD_ROLLOUT_STOP_TOKEN_IDS
  OPD_SEQ_LENGTH
  OPD_MAX_TOKENS_PER_GPU
  OPD_LOG_PROBS_CHUNK_SIZE
  OPD_TRAIN_MEMORY_MARGIN_BYTES
  OPD_LR
  OPD_SAVE_INTERVAL
  OPD_ACTOR_GPUS
  OPD_ROLLOUT_GPUS
  OPD_RAY_GPUS
  OPD_TEACHER_GPU
  OPD_TENSOR_MODEL_PARALLEL_SIZE
  OPD_CONTEXT_PARALLEL_SIZE
  OPD_TEACHER_PORT
  OPD_TEACHER_MEM_FRACTION
  OPD_DISABLE_CUDA_GRAPH
  SLIME_SGLANG_FORCE_NATIVE_ROPE
  SLIME_SGLANG_PATCH_SITE
  SLIME_VLLM_PATCH_SITE
  SLIME_SGLANG_PYTORCH_CUDA_ALLOC_CONF
  OPD_SGLANG_RL_ON_POLICY_TARGET
  OPD_COLOCATE
  OPD_OFFLOAD_TRAIN
  OPD_OFFLOAD_ROLLOUT
  OPD_RECOMPUTE_LOSS_FUNCTION
  OPD_INITIAL_LOAD_MODE
  OPD_INITIAL_LOAD_DIR
  OPD_REF_LOAD_DIR
  OPD_OPTIMIZER_CPU_OFFLOAD
  OPD_ALLOW_OPT_PARAM_SCHEDULER_MISMATCH
  OPD_SKIP_ROLLOUT_DATA_STATE_LOAD
  OPD_ALREADY_TRAINED_SAMPLES
  OPD_START_ROLLOUT_ID
  OPD_PREVIOUS_RUN_LABEL
  OPD_PREVIOUS_SAVE_DIR
  OPD_PREVIOUS_HF_SNAPSHOT_DIR
  OPD_PREVIOUS_ROLLOUT_LOG_DIR
  OPD_PREVIOUS_TRAINED_MANIFEST
  OPD_CONTINUATION_METADATA
  OPD_MANIFEST_FROM_ROLLOUT_LOGS
  OPD_TRAINED_MANIFEST
  OPD_RETIRE_PREVIOUS_FULL_SAVE_DIR
  OPD_RETIRE_PREVIOUS_HF_DIR
  OPD_SANITY_CHECK_ENABLED
  OPD_SANITY_FAIL_ON_COLLAPSE
  OPD_SANITY_MAX_ROLLOUT_ID
  OPD_SANITY_MAX_CAP_HIT_RATE
  OPD_SANITY_MAX_AVG_RESPONSE_TOKENS
  OPD_SANITY_MIN_FINAL_ANSWER_RATE
  OPD_SANITY_REPORT_DIR
  OPD_SANITY_SUMMARY_DIR
  CHECKPOINT_PRUNE_INTERVAL_SECONDS
  ESTIMATED_FULL_OPTIM_CKPT_BYTES
  EVAL_MAX_RESPONSE_LEN
  EVAL_MAX_CONTEXT_LEN
  EVAL_STOP_TOKEN_IDS
  EVAL_BACKEND
  EVAL_ROLLOUT_BATCH_SIZE
  EVAL_ROLLOUT_NUM_GPUS
  EVAL_TENSOR_MODEL_PARALLEL_SIZE
  EVAL_CONTEXT_PARALLEL_SIZE
  EVAL_MAX_TOKENS_PER_GPU
  EVAL_NUM_REPEATS
  EVAL_SGLANG_SERVER_CONCURRENCY
  EVAL_DISABLE_CUDA_GRAPH
  EVAL_SGLANG_RL_ON_POLICY_TARGET
  EVAL_SKIP_COMPLETED
  EVAL_EXPECTED_SAMPLES
  EVAL_TARGETS
  EVAL_MODE
  EVAL_MODEL_DIR
  EVAL_TOKENIZER_DIR
  EVAL_LABEL
  EVAL_STAGE_DIR
  EVAL_TUNING_FILE
  EVAL_4B_BASE_DIR
  EVAL_32B_BASE_DIR
  EVAL_OPD1K_DIR
  EVAL_OPD5120_DIR
  BASE_REPORT_DIR
  FINAL_REPORT_DIR
  REPORT_INCLUDE_SFT
  REPORT_MODE
  REPORT_OPD_X_OFFSET_SAMPLES
  REPORT_OPD_LABEL_PREFIX
  REPORT_SFT_FINAL_ONLY
  REPORT_OPD_FINAL_ONLY
  REPORT_EXPERIMENT_NOTE
  VLLM_EVAL_VENV
  VLLM_EVAL_SITE
  VLLM_EVAL_PYTHON
  VLLM_EVAL_PYTHON_CMD
  VLLM_EVAL_INSTALL_SPEC
  VLLM_EVAL_PIP_EXTRA_INDEX_URL
  VLLM_EVAL_NUM_GPUS
  VLLM_EVAL_MAX_MODEL_LEN
  VLLM_EVAL_MAX_RESPONSE_LEN
  VLLM_EVAL_BENCHMARK_SIZE
  VLLM_EVAL_BENCHMARK_MAX_TOKENS
  VLLM_EVAL_GPU_MEMORY_UTILIZATION
  VLLM_EVAL_MAX_NUM_SEQS
  VLLM_EVAL_MAX_NUM_BATCHED_TOKENS
  VLLM_EVAL_KV_CACHE_DTYPE
  VLLM_EVAL_ENABLE_PREFIX_CACHING
  VLLM_EVAL_ENABLE_CHUNKED_PREFILL
  VLLM_EVAL_ASYNC_SCHEDULING
  VLLM_EVAL_SAFETENSORS_LOAD_STRATEGY
  VLLM_EVAL_SPECULATIVE_METHOD
  VLLM_EVAL_NUM_SPECULATIVE_TOKENS
  VLLM_EVAL_PROMPT_LOOKUP_MIN
  VLLM_EVAL_PROMPT_LOOKUP_MAX
  VLLM_EVAL_CHUNK_SIZE
  VLLM_EVAL_RESUME_COMPLETED
  VLLM_EVAL_PRESERVE_SPECIAL_TOKENS
  VLLM_EVAL_DTYPE
  VLLM_EVAL_TRUST_REMOTE_CODE
  VLLM_EVAL_FORCE_NATIVE_SAMPLER
  OPD_PROMPT_CONTRACT_VERSION
  OPD1_SAVE_DIR
  OPD1_HF_DIR
  OPD1_ROLLOUT_LOG_DIR
  OPD1_SANITY_DIR
  OPD_CONT_SAVE_DIR
  OPD_CONT_HF_DIR
  OPD_CONT_ROLLOUT_LOG_DIR
  OPD_CONT_SANITY_DIR
  OPD_TUNING_ROOT
  OPD_TUNING_FILE
  PYTHONUNBUFFERED
  TOKENIZERS_PARALLELISM
  NCCL_DEBUG
  PYTORCH_CUDA_ALLOC_CONF
  LD_LIBRARY_PATH
)

export_container_env() {
  local name="$1"
  local value="$2"
  if [[ "${value}" == *$'\n'* || "${value}" == *$'\r'* ]]; then
    cat >&2 <<EOF
Cannot forward ${name} into the Apptainer container because it contains a newline.
Container env forwarding supports spaces and commas, but not multiline values.
EOF
    exit 1
  fi

  # Apptainer/Singularity split --env values on commas. Prefix-based forwarding
  # preserves long notes and paths containing spaces, commas, or punctuation.
  export "APPTAINERENV_${name}=${value}"
  export "SINGULARITYENV_${name}=${value}"
}

for name in "${PASS_ENV[@]}"; do
  if [[ "${!name+x}" == "x" ]]; then
    export_container_env "${name}" "${!name}"
  fi
done

export_container_env PYTHONPATH "${SLIME_REPO_ROOT}:/root/Megatron-LM:${PYTHONPATH:-}"
export_container_env CUDA_DEVICE_MAX_CONNECTIONS "${CUDA_DEVICE_MAX_CONNECTIONS:-1}"

container_path_exists() {
  local path="$1"
  if [[ -d "${SLIME_SIF}" ]]; then
    [[ -e "${SLIME_SIF}${path}" ]]
  else
    "${APPTAINER_BIN}" "${APPTAINER_ARGS[@]}" "${SLIME_SIF}" test -e "${path}"
  fi
}

container_has_py_or_legacy_pyc() {
  local module_path="$1"
  container_path_exists "${module_path}.py" || container_path_exists "${module_path}.pyc"
}

check_stdlib_files() {
  local missing=()
  for module_path in \
    /usr/lib/python3.12/encodings/__init__ \
    /usr/lib/python3.12/os \
    /usr/lib/python3.12/site; do
    if ! container_has_py_or_legacy_pyc "${module_path}"; then
      missing+=("${module_path}.py or ${module_path}.pyc")
    fi
  done

  if [[ "${#missing[@]}" -gt 0 ]]; then
    cat >&2 <<EOF
Container Python stdlib preflight failed before launching the requested command.
The sandbox appears to be pycache-only and not sourceless-import materialized:
  ${SLIME_SIF}

Missing source or legacy sourceless .pyc paths:
EOF
    printf "  %s\n" "${missing[@]}" >&2
    cat >&2 <<EOF

Repair or rebuild it with:
  bash ${SCRIPT_DIR}/00_pull_or_load_container.sh
EOF
    return 1
  fi
}

if [[ "${CONTAINER_PYTHON_PREFLIGHT:-1}" != "0" ]]; then
  check_stdlib_files
  preflight_log="$(mktemp "${TMPDIR%/}/container_python_preflight.XXXXXX")"
  if ! "${APPTAINER_BIN}" "${APPTAINER_ARGS[@]}" "${SLIME_SIF}" \
    python3 -c "import encodings, os, site" >/dev/null 2>"${preflight_log}"; then
    if grep -Eq 'invalid argument|unknown flag|requires an argument|must be formatted as key=value' "${preflight_log}"; then
      cat >&2 <<EOF
Container launch failed before Python preflight could run.
This is an Apptainer/Singularity command-line or environment-forwarding error:
  ${SLIME_SIF}

Launch stderr:
EOF
    else
      cat >&2 <<EOF
Container Python preflight failed before launching the requested command.
The container may be incomplete or corrupt:
  ${SLIME_SIF}

Python could not import required stdlib modules. The sandbox may be pycache-only
and not sourceless-import materialized. Repair or rebuild it with:
  bash ${SCRIPT_DIR}/00_pull_or_load_container.sh

Preflight stderr:
EOF
    fi
    sed -n '1,120p' "${preflight_log}" >&2 || true
    rm -f "${preflight_log}"
    exit 1
  fi
  rm -f "${preflight_log}"
fi

"${APPTAINER_BIN}" "${APPTAINER_ARGS[@]}" "${SLIME_SIF}" "$@"
