#!/usr/bin/env bash

# Source this file from the repository root or from any script in this
# directory. All generated state is kept under scrubbed/scratch storage.

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "Source this file instead of executing it:"
  echo "  source ${BASH_SOURCE[0]}"
  exit 2
fi

export TILLICUM_EXAMPLE_DIR
TILLICUM_EXAMPLE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

export SLIME_REPO_ROOT
SLIME_REPO_ROOT="$(cd -- "${TILLICUM_EXAMPLE_DIR}/../.." >/dev/null 2>&1 && pwd)"

export ACCOUNT="${ACCOUNT:-raivn}"
export PARTITION="${PARTITION:-gpu-h200}"
export QOS="${QOS:-normal}"

export SCRATCH_ROOT="${SCRATCH_ROOT:-/gpfs/scrubbed/suryadv/slime-qwen3-8b-opd}"
export DATA_ROOT="${DATA_ROOT:-${SCRATCH_ROOT}/data}"
export MODEL_ROOT="${MODEL_ROOT:-${SCRATCH_ROOT}/models}"
export OUTPUT_ROOT="${OUTPUT_ROOT:-${SCRATCH_ROOT}/outputs}"
export HF_HOME="${HF_HOME:-${SCRATCH_ROOT}/hf_home}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-${HF_HOME}/datasets}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/transformers}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export WANDB_DIR="${WANDB_DIR:-${OUTPUT_ROOT}/wandb}"
export TMPDIR="${TMPDIR:-${SCRATCH_ROOT}/tmp}"
export RAY_TMPDIR="${RAY_TMPDIR:-${SCRATCH_ROOT}/ray_tmp}"

export APPTAINER_CACHEDIR="${APPTAINER_CACHEDIR:-${SCRATCH_ROOT}/apptainer_cache}"
export APPTAINER_TMPDIR="${APPTAINER_TMPDIR:-${SCRATCH_ROOT}/apptainer_tmp}"
export SLIME_IMAGE_URI="${SLIME_IMAGE_URI:-docker://slimerl/slime:latest}"
export SLIME_CONTAINER_FORMAT="${SLIME_CONTAINER_FORMAT:-sandbox}"
if [[ -z "${SLIME_SIF:-}" ]]; then
  if [[ "${SLIME_CONTAINER_FORMAT}" == "sandbox" ]]; then
    export SLIME_SIF="${SCRATCH_ROOT}/containers/slime_latest.sandbox"
  else
    export SLIME_SIF="${SCRATCH_ROOT}/containers/slime_latest.sif"
  fi
else
  export SLIME_SIF
fi
export CONTAINER_BIND_ROOTS="${CONTAINER_BIND_ROOTS:-/gpfs/scrubbed/suryadv,/tmp}"
export CONTAINER_HOME="${CONTAINER_HOME:-${SCRATCH_ROOT}/container_home}"
export CONTAINER_HOME_INNER="${CONTAINER_HOME_INNER:-/home/${USER:-slime}}"

export STUDENT_HF_REPO="${STUDENT_HF_REPO:-Qwen/Qwen3-8B-Base}"
export TEACHER_HF_REPO="${TEACHER_HF_REPO:-Qwen/Qwen3-32B}"
export OT3_DATASET="${OT3_DATASET:-open-thoughts/OpenThoughts3-1.2M}"
export MATH500_DATASET="${MATH500_DATASET:-HuggingFaceH4/MATH-500}"
export QWEN3_ENABLE_THINKING="${QWEN3_ENABLE_THINKING:-1}"
export QWEN3_IM_END_TOKEN_ID="${QWEN3_IM_END_TOKEN_ID:-151645}"
export QWEN3_ENDOFTEXT_TOKEN_ID="${QWEN3_ENDOFTEXT_TOKEN_ID:-151643}"
export QWEN3_STOP_TOKEN_IDS="${QWEN3_STOP_TOKEN_IDS:-${QWEN3_IM_END_TOKEN_ID} ${QWEN3_ENDOFTEXT_TOKEN_ID}}"

export STUDENT_HF_DIR="${STUDENT_HF_DIR:-${MODEL_ROOT}/Qwen3-8B-Base}"
export TEACHER_HF_DIR="${TEACHER_HF_DIR:-${MODEL_ROOT}/Qwen3-32B}"
export STUDENT_TORCH_DIST_DIR="${STUDENT_TORCH_DIST_DIR:-${MODEL_ROOT}/Qwen3-8B-Base_torch_dist}"

export SFT_SIZE="${SFT_SIZE:-25000}"
export OPD_POOL_SIZE="${OPD_POOL_SIZE:-${OPD_SIZE:-10000}}"
export OPD_TRAIN_SIZE="${OPD_TRAIN_SIZE:-1024}"
export OPD_SIZE="${OPD_SIZE:-${OPD_POOL_SIZE}}"
export OPD_RUN_LABEL="${OPD_RUN_LABEL:-1k_32k}"
export DATA_SEED="${DATA_SEED:-1234}"
export DATA_MATH_FIELD="${DATA_MATH_FIELD:-domain}"
export DATA_MATH_VALUE="${DATA_MATH_VALUE:-math}"
export OT3_SPLIT="${OT3_SPLIT:-train}"

export SFT_PARQUET="${SFT_PARQUET:-${DATA_ROOT}/openthoughts3_math_sft_${SFT_SIZE}.jsonl}"
export OPD_JSONL="${OPD_JSONL:-${DATA_ROOT}/openthoughts3_math_opd_${OPD_POOL_SIZE}.jsonl}"
export SPLIT_METADATA="${SPLIT_METADATA:-${DATA_ROOT}/openthoughts3_math_sft_${SFT_SIZE}_opd_${OPD_POOL_SIZE}_metadata.json}"
export CLEANED_EXPERIMENT_LABEL="${CLEANED_EXPERIMENT_LABEL:-cleaned_think_sft25k_opd5k_vllm}"
export CLEANED_OPD_FIRST_SIZE="${CLEANED_OPD_FIRST_SIZE:-1024}"
export CLEANED_OPD_NEXT_SIZE="${CLEANED_OPD_NEXT_SIZE:-4096}"
export CLEANED_METADATA="${CLEANED_METADATA:-${DATA_ROOT}/openthoughts3_cleaned_${CLEANED_EXPERIMENT_LABEL}_metadata.json}"
export CLEANED_OPD_RESERVE_JSONL="${CLEANED_OPD_RESERVE_JSONL:-${DATA_ROOT}/openthoughts3_cleaned_${CLEANED_EXPERIMENT_LABEL}_opd_reserve.jsonl}"
export CLEANED_OPD_1K_JSONL="${CLEANED_OPD_1K_JSONL:-${DATA_ROOT}/openthoughts3_cleaned_${CLEANED_EXPERIMENT_LABEL}_opd_001024.jsonl}"
export CLEANED_OPD_4K_JSONL="${CLEANED_OPD_4K_JSONL:-${DATA_ROOT}/openthoughts3_cleaned_${CLEANED_EXPERIMENT_LABEL}_opd_next_004096.jsonl}"
export MATH500_JSONL="${MATH500_JSONL:-${DATA_ROOT}/math500_deepscaler.jsonl}"
export MATH500_CONFIG="${MATH500_CONFIG:-${DATA_ROOT}/math500_eval.yaml}"
export MATH500_VAL100_SEED="${MATH500_VAL100_SEED:-1234}"
export MATH500_VAL100_SIZE="${MATH500_VAL100_SIZE:-100}"
export MATH500_VAL100_JSONL="${MATH500_VAL100_JSONL:-${DATA_ROOT}/math500_val100_seed${MATH500_VAL100_SEED}.jsonl}"
export MATH500_VAL100_CONFIG="${MATH500_VAL100_CONFIG:-${DATA_ROOT}/math500_val100_seed${MATH500_VAL100_SEED}_eval.yaml}"
export MATH500_VAL100_METADATA="${MATH500_VAL100_METADATA:-${DATA_ROOT}/math500_val100_seed${MATH500_VAL100_SEED}_metadata.json}"

export SFT_SAVE_DIR="${SFT_SAVE_DIR:-${OUTPUT_ROOT}/qwen3_8b_sft_25k_full_optim}"
export OPD_SAVE_DIR="${OPD_SAVE_DIR:-${OUTPUT_ROOT}/qwen3_8b_sft_25k_opd_${OPD_RUN_LABEL}_full_optim}"
export SFT_HF_SNAPSHOT_DIR="${SFT_HF_SNAPSHOT_DIR:-${OUTPUT_ROOT}/qwen3_8b_sft_25k_eval_snapshots}"
export OPD_HF_SNAPSHOT_DIR="${OPD_HF_SNAPSHOT_DIR:-${OUTPUT_ROOT}/qwen3_8b_sft_25k_opd_${OPD_RUN_LABEL}_eval_snapshots}"
export SFT_DETAILS_DIR="${SFT_DETAILS_DIR:-${OUTPUT_ROOT}/sft_25k_details}"
export OPD_ROLLOUT_LOG_DIR="${OPD_ROLLOUT_LOG_DIR:-${OUTPUT_ROOT}/opd_${OPD_RUN_LABEL}_rollout_logs}"
export TEACHER_LOG_DIR="${TEACHER_LOG_DIR:-${OUTPUT_ROOT}/teacher_logs}"
export EVAL_OUTPUT_DIR="${EVAL_OUTPUT_DIR:-${OUTPUT_ROOT}/math500_eval_25k_opd_${OPD_RUN_LABEL}}"
export BASE_EVAL_OUTPUT_DIR="${BASE_EVAL_OUTPUT_DIR:-${OUTPUT_ROOT}/math500_eval_base_25k_opd_${OPD_RUN_LABEL}}"
export SFT_EVAL_OUTPUT_DIR="${SFT_EVAL_OUTPUT_DIR:-${OUTPUT_ROOT}/math500_eval_sft_25k_curve}"
export OPD_EVAL_OUTPUT_DIR="${OPD_EVAL_OUTPUT_DIR:-${OUTPUT_ROOT}/math500_eval_opd_${OPD_RUN_LABEL}_final}"
export COMBINED_EVAL_OUTPUT_DIR="${COMBINED_EVAL_OUTPUT_DIR:-${OUTPUT_ROOT}/math500_eval_combined_25k_opd_${OPD_RUN_LABEL}}"
export CHECKPOINT_REPORT_DIR="${CHECKPOINT_REPORT_DIR:-${OUTPUT_ROOT}/checkpoint_reports_25k_opd_${OPD_RUN_LABEL}}"
export SLURM_LOG_DIR="${SLURM_LOG_DIR:-${OUTPUT_ROOT}/slurm_logs}"

export SFT_NUM_EPOCH="${SFT_NUM_EPOCH:-1}"
export SFT_ROLLOUT_BATCH_SIZE="${SFT_ROLLOUT_BATCH_SIZE:-256}"
export SFT_GLOBAL_BATCH_SIZE="${SFT_GLOBAL_BATCH_SIZE:-256}"
export SFT_MAX_TOKENS_PER_GPU="${SFT_MAX_TOKENS_PER_GPU:-16384}"
export SFT_ACTOR_GPUS="${SFT_ACTOR_GPUS:-8}"
export SFT_TENSOR_MODEL_PARALLEL_SIZE="${SFT_TENSOR_MODEL_PARALLEL_SIZE:-2}"
export SFT_CONTEXT_PARALLEL_SIZE="${SFT_CONTEXT_PARALLEL_SIZE:-1}"
export SFT_PIPELINE_MODEL_PARALLEL_SIZE="${SFT_PIPELINE_MODEL_PARALLEL_SIZE:-1}"
export SFT_ZERO_STAGE="${SFT_ZERO_STAGE:-1}"
export SFT_LR="${SFT_LR:-1e-6}"
export SFT_CKPT_FORMAT="${SFT_CKPT_FORMAT:-torch_dist}"
export SFT_SAVE_INTERVAL="${SFT_SAVE_INTERVAL:-20}"
export SFT_NUM_ROLLOUT="${SFT_NUM_ROLLOUT:-$((SFT_SIZE / SFT_ROLLOUT_BATCH_SIZE))}"
export SFT_FINAL_ROLLOUT_ID="${SFT_FINAL_ROLLOUT_ID:-$((SFT_NUM_ROLLOUT - 1))}"
export SFT_MILESTONE_ROLLOUT_IDS="${SFT_MILESTONE_ROLLOUT_IDS:-19 39 59 79 ${SFT_FINAL_ROLLOUT_ID}}"
_SFT_HF_SNAPSHOT_TEMPLATE_DEFAULT="${SFT_HF_SNAPSHOT_DIR}/iter_{rollout_id:07d}"
export SFT_HF_SNAPSHOT_TEMPLATE="${SFT_HF_SNAPSHOT_TEMPLATE:-${_SFT_HF_SNAPSHOT_TEMPLATE_DEFAULT}}"
while [[ "${SFT_HF_SNAPSHOT_TEMPLATE}" =~ \{rollout_id:07d\}\}+$ ]]; do
  SFT_HF_SNAPSHOT_TEMPLATE="${SFT_HF_SNAPSHOT_TEMPLATE%\}}"
done
unset _SFT_HF_SNAPSHOT_TEMPLATE_DEFAULT
printf -v _SFT_FINAL_ROLLOUT_TAG "iter_%07d" "${SFT_FINAL_ROLLOUT_ID}"
export SFT_FINAL_HF_DIR="${SFT_FINAL_HF_DIR:-${SFT_HF_SNAPSHOT_DIR}/${_SFT_FINAL_ROLLOUT_TAG}}"
unset _SFT_FINAL_ROLLOUT_TAG
printf -v _SFT_FINAL_FULL_CKPT_TAG "iter_%07d" "${SFT_FINAL_ROLLOUT_ID}"
export SFT_FINAL_FULL_CKPT_DIR="${SFT_FINAL_FULL_CKPT_DIR:-${SFT_SAVE_DIR}/${_SFT_FINAL_FULL_CKPT_TAG}}"
unset _SFT_FINAL_FULL_CKPT_TAG

export OPD_ROLLOUT_BATCH_SIZE="${OPD_ROLLOUT_BATCH_SIZE:-128}"
export OPD_GLOBAL_BATCH_SIZE="${OPD_GLOBAL_BATCH_SIZE:-128}"
export OPD_N_SAMPLES_PER_PROMPT="${OPD_N_SAMPLES_PER_PROMPT:-1}"
export OPD_NUM_ROLLOUT="${OPD_NUM_ROLLOUT:-$((OPD_TRAIN_SIZE / OPD_ROLLOUT_BATCH_SIZE))}"
export OPD_FINAL_ROLLOUT_ID="${OPD_FINAL_ROLLOUT_ID:-$((OPD_NUM_ROLLOUT - 1))}"
export OPD_EFFECTIVE_TRAIN_SAMPLES="${OPD_EFFECTIVE_TRAIN_SAMPLES:-$((OPD_NUM_ROLLOUT * OPD_ROLLOUT_BATCH_SIZE))}"
export OPD_MILESTONE_ROLLOUT_IDS="${OPD_MILESTONE_ROLLOUT_IDS:-${OPD_FINAL_ROLLOUT_ID}}"
export OPD_MAX_RESPONSE_LEN="${OPD_MAX_RESPONSE_LEN:-31744}"
export OPD_SEQ_LENGTH="${OPD_SEQ_LENGTH:-32766}"
export OPD_ROLLOUT_MAX_CONTEXT_LEN="${OPD_ROLLOUT_MAX_CONTEXT_LEN:-${OPD_SEQ_LENGTH}}"
export OPD_ROLLOUT_STOP_TOKEN_IDS="${OPD_ROLLOUT_STOP_TOKEN_IDS:-${QWEN3_STOP_TOKEN_IDS}}"
export OPD_MAX_TOKENS_PER_GPU="${OPD_MAX_TOKENS_PER_GPU:-11264}"
export OPD_LOG_PROBS_CHUNK_SIZE="${OPD_LOG_PROBS_CHUNK_SIZE:-4096}"
export OPD_TRAIN_MEMORY_MARGIN_BYTES="${OPD_TRAIN_MEMORY_MARGIN_BYTES:-1073741824}"
export OPD_LR="${OPD_LR:-1e-6}"
export OPD_SAVE_INTERVAL="${OPD_SAVE_INTERVAL:-8}"
_OPD_HF_SNAPSHOT_TEMPLATE_DEFAULT="${OPD_HF_SNAPSHOT_DIR}/iter_{rollout_id:07d}"
export OPD_HF_SNAPSHOT_TEMPLATE="${OPD_HF_SNAPSHOT_TEMPLATE:-${_OPD_HF_SNAPSHOT_TEMPLATE_DEFAULT}}"
while [[ "${OPD_HF_SNAPSHOT_TEMPLATE}" =~ \{rollout_id:07d\}\}+$ ]]; do
  OPD_HF_SNAPSHOT_TEMPLATE="${OPD_HF_SNAPSHOT_TEMPLATE%\}}"
done
unset _OPD_HF_SNAPSHOT_TEMPLATE_DEFAULT
printf -v _OPD_FINAL_ROLLOUT_TAG "iter_%07d" "${OPD_FINAL_ROLLOUT_ID}"
export OPD_FINAL_HF_DIR="${OPD_FINAL_HF_DIR:-${OPD_HF_SNAPSHOT_DIR}/${_OPD_FINAL_ROLLOUT_TAG}}"
unset _OPD_FINAL_ROLLOUT_TAG
export OPD_ACTOR_GPUS="${OPD_ACTOR_GPUS:-6}"
export OPD_ROLLOUT_GPUS="${OPD_ROLLOUT_GPUS:-1}"
export OPD_RAY_GPUS="${OPD_RAY_GPUS:-7}"
export OPD_TEACHER_GPU="${OPD_TEACHER_GPU:-7}"
export OPD_TENSOR_MODEL_PARALLEL_SIZE="${OPD_TENSOR_MODEL_PARALLEL_SIZE:-2}"
export OPD_CONTEXT_PARALLEL_SIZE="${OPD_CONTEXT_PARALLEL_SIZE:-3}"
export OPD_TEACHER_PORT="${OPD_TEACHER_PORT:-13141}"
export OPD_TEACHER_MEM_FRACTION="${OPD_TEACHER_MEM_FRACTION:-0.6}"
export OPD_DISABLE_CUDA_GRAPH="${OPD_DISABLE_CUDA_GRAPH:-1}"
# The Tillicum sandbox lacks a full GCC/CUDA development toolchain, so use
# Slime's narrow SGLang RoPE shim instead of runtime fused-RoPE compilation.
export SLIME_SGLANG_FORCE_NATIVE_ROPE="${SLIME_SGLANG_FORCE_NATIVE_ROPE:-1}"
export SLIME_SGLANG_PATCH_SITE="${SLIME_SGLANG_PATCH_SITE:-${SLIME_SGLANG_FORCE_NATIVE_ROPE}}"
export OPD_SGLANG_RL_ON_POLICY_TARGET="${OPD_SGLANG_RL_ON_POLICY_TARGET-}"
export OPD_COLOCATE="${OPD_COLOCATE:-0}"
export OPD_OFFLOAD_TRAIN="${OPD_OFFLOAD_TRAIN:-0}"
export OPD_OFFLOAD_ROLLOUT="${OPD_OFFLOAD_ROLLOUT:-0}"
export OPD_RECOMPUTE_LOSS_FUNCTION="${OPD_RECOMPUTE_LOSS_FUNCTION:-0}"
export OPD_INITIAL_LOAD_MODE="${OPD_INITIAL_LOAD_MODE:-megatron}"
case "${OPD_INITIAL_LOAD_MODE}" in
  megatron|hf) ;;
  *)
    echo "OPD_INITIAL_LOAD_MODE must be 'megatron' or 'hf', got '${OPD_INITIAL_LOAD_MODE}'" >&2
    return 1
    ;;
esac
if [[ -z "${OPD_INITIAL_LOAD_DIR:-}" ]]; then
  if [[ "${OPD_INITIAL_LOAD_MODE}" == "hf" ]]; then
    export OPD_INITIAL_LOAD_DIR="${SFT_FINAL_HF_DIR}"
  else
    export OPD_INITIAL_LOAD_DIR="${SFT_SAVE_DIR}"
  fi
else
  export OPD_INITIAL_LOAD_DIR
fi
export OPD_REF_LOAD_DIR="${OPD_REF_LOAD_DIR:-${STUDENT_TORCH_DIST_DIR}}"
export OPD_OPTIMIZER_CPU_OFFLOAD="${OPD_OPTIMIZER_CPU_OFFLOAD:-0}"
export OPD_ALLOW_OPT_PARAM_SCHEDULER_MISMATCH="${OPD_ALLOW_OPT_PARAM_SCHEDULER_MISMATCH:-0}"
export OPD_SKIP_ROLLOUT_DATA_STATE_LOAD="${OPD_SKIP_ROLLOUT_DATA_STATE_LOAD:-0}"
export OPD_ALREADY_TRAINED_SAMPLES="${OPD_ALREADY_TRAINED_SAMPLES:-0}"
export OPD_START_ROLLOUT_ID="${OPD_START_ROLLOUT_ID:-0}"
export OPD_PREVIOUS_RUN_LABEL="${OPD_PREVIOUS_RUN_LABEL:-1k_32k_sft_colocate4}"
export OPD_PREVIOUS_SAVE_DIR="${OPD_PREVIOUS_SAVE_DIR:-${OUTPUT_ROOT}/qwen3_8b_sft_25k_opd_${OPD_PREVIOUS_RUN_LABEL}_full_optim}"
export OPD_PREVIOUS_HF_SNAPSHOT_DIR="${OPD_PREVIOUS_HF_SNAPSHOT_DIR:-${OUTPUT_ROOT}/qwen3_8b_sft_25k_opd_${OPD_PREVIOUS_RUN_LABEL}_eval_snapshots}"
export OPD_PREVIOUS_ROLLOUT_LOG_DIR="${OPD_PREVIOUS_ROLLOUT_LOG_DIR:-${OUTPUT_ROOT}/opd_${OPD_PREVIOUS_RUN_LABEL}_rollout_logs}"
export OPD_PREVIOUS_TRAINED_MANIFEST="${OPD_PREVIOUS_TRAINED_MANIFEST:-${OPD_PREVIOUS_SAVE_DIR}/opd_trained_manifest.json}"
export OPD_CONTINUATION_METADATA="${OPD_CONTINUATION_METADATA:-${SPLIT_METADATA}}"
export OPD_MANIFEST_FROM_ROLLOUT_LOGS="${OPD_MANIFEST_FROM_ROLLOUT_LOGS:-0}"
export OPD_TRAINED_MANIFEST="${OPD_TRAINED_MANIFEST:-${OPD_SAVE_DIR}/opd_trained_manifest.json}"
export OPD_SANITY_CHECK_ENABLED="${OPD_SANITY_CHECK_ENABLED:-1}"
export OPD_SANITY_FAIL_ON_COLLAPSE="${OPD_SANITY_FAIL_ON_COLLAPSE:-1}"
export OPD_SANITY_MAX_ROLLOUT_ID="${OPD_SANITY_MAX_ROLLOUT_ID:-${OPD_FINAL_ROLLOUT_ID}}"
export OPD_SANITY_MAX_CAP_HIT_RATE="${OPD_SANITY_MAX_CAP_HIT_RATE:-0.50}"
export OPD_SANITY_MAX_AVG_RESPONSE_TOKENS="${OPD_SANITY_MAX_AVG_RESPONSE_TOKENS:-16000}"
export OPD_SANITY_MIN_FINAL_ANSWER_RATE="${OPD_SANITY_MIN_FINAL_ANSWER_RATE:-0.02}"
export OPD_SANITY_REPORT_DIR="${OPD_SANITY_REPORT_DIR:-${OUTPUT_ROOT}/opd_${OPD_RUN_LABEL}_sanity}"
export OPD_SANITY_SUMMARY_DIR="${OPD_SANITY_SUMMARY_DIR:-${OPD_SANITY_REPORT_DIR}}"
export CHECKPOINT_PRUNE_INTERVAL_SECONDS="${CHECKPOINT_PRUNE_INTERVAL_SECONDS:-60}"
export ESTIMATED_FULL_OPTIM_CKPT_BYTES="${ESTIMATED_FULL_OPTIM_CKPT_BYTES:-114694164347}"

export EVAL_MAX_RESPONSE_LEN="${EVAL_MAX_RESPONSE_LEN:-31744}"
export EVAL_MAX_CONTEXT_LEN="${EVAL_MAX_CONTEXT_LEN:-32768}"
export EVAL_STOP_TOKEN_IDS="${EVAL_STOP_TOKEN_IDS:-${QWEN3_STOP_TOKEN_IDS}}"
export EVAL_BACKEND="${EVAL_BACKEND:-sglang}"
export EVAL_ROLLOUT_BATCH_SIZE="${EVAL_ROLLOUT_BATCH_SIZE:-64}"
export EVAL_ROLLOUT_NUM_GPUS="${EVAL_ROLLOUT_NUM_GPUS:-8}"
export EVAL_TENSOR_MODEL_PARALLEL_SIZE="${EVAL_TENSOR_MODEL_PARALLEL_SIZE:-2}"
export EVAL_CONTEXT_PARALLEL_SIZE="${EVAL_CONTEXT_PARALLEL_SIZE:-1}"
export EVAL_MAX_TOKENS_PER_GPU="${EVAL_MAX_TOKENS_PER_GPU:-${EVAL_MAX_RESPONSE_LEN}}"
export EVAL_NUM_REPEATS="${EVAL_NUM_REPEATS:-1}"
export EVAL_SGLANG_SERVER_CONCURRENCY="${EVAL_SGLANG_SERVER_CONCURRENCY:-1}"
export EVAL_DISABLE_CUDA_GRAPH="${EVAL_DISABLE_CUDA_GRAPH:-1}"
export EVAL_SGLANG_RL_ON_POLICY_TARGET="${EVAL_SGLANG_RL_ON_POLICY_TARGET-}"
export EVAL_SKIP_COMPLETED="${EVAL_SKIP_COMPLETED:-1}"
export EVAL_EXPECTED_SAMPLES="${EVAL_EXPECTED_SAMPLES:-500}"
export EVAL_TARGETS="${EVAL_TARGETS:-base sft opd}"
export REPORT_INCLUDE_SFT="${REPORT_INCLUDE_SFT:-1}"
export REPORT_OPD_X_OFFSET_SAMPLES="${REPORT_OPD_X_OFFSET_SAMPLES:-$((SFT_NUM_ROLLOUT * SFT_ROLLOUT_BATCH_SIZE))}"
export REPORT_OPD_LABEL_PREFIX="${REPORT_OPD_LABEL_PREFIX-SFT+}"
export REPORT_SFT_FINAL_ONLY="${REPORT_SFT_FINAL_ONLY:-1}"
export REPORT_OPD_FINAL_ONLY="${REPORT_OPD_FINAL_ONLY:-1}"

export VLLM_EVAL_VENV="${VLLM_EVAL_VENV:-${SCRATCH_ROOT}/vllm_eval_venv}"
export VLLM_EVAL_SITE="${VLLM_EVAL_SITE:-${SCRATCH_ROOT}/vllm_eval_site}"
export VLLM_EVAL_PYTHON="${VLLM_EVAL_PYTHON:-python3}"
export VLLM_EVAL_INSTALL_SPEC="${VLLM_EVAL_INSTALL_SPEC:-vllm}"
export VLLM_EVAL_PIP_EXTRA_INDEX_URL="${VLLM_EVAL_PIP_EXTRA_INDEX_URL:-https://download.pytorch.org/whl/cu129}"
export VLLM_EVAL_NUM_GPUS="${VLLM_EVAL_NUM_GPUS:-4}"
export VLLM_EVAL_MAX_MODEL_LEN="${VLLM_EVAL_MAX_MODEL_LEN:-32768}"
export VLLM_EVAL_GPU_MEMORY_UTILIZATION="${VLLM_EVAL_GPU_MEMORY_UTILIZATION:-0.92}"
export VLLM_EVAL_MAX_NUM_SEQS="${VLLM_EVAL_MAX_NUM_SEQS:-16}"
export VLLM_EVAL_MAX_NUM_BATCHED_TOKENS="${VLLM_EVAL_MAX_NUM_BATCHED_TOKENS:-131072}"
export VLLM_EVAL_CHUNK_SIZE="${VLLM_EVAL_CHUNK_SIZE:-16}"
export VLLM_EVAL_RESUME_COMPLETED="${VLLM_EVAL_RESUME_COMPLETED:-1}"
export VLLM_EVAL_PRESERVE_SPECIAL_TOKENS="${VLLM_EVAL_PRESERVE_SPECIAL_TOKENS:-1}"
export VLLM_EVAL_DTYPE="${VLLM_EVAL_DTYPE:-bfloat16}"
export VLLM_EVAL_TRUST_REMOTE_CODE="${VLLM_EVAL_TRUST_REMOTE_CODE:-1}"
export VLLM_EVAL_FORCE_NATIVE_SAMPLER="${VLLM_EVAL_FORCE_NATIVE_SAMPLER:-1}"
export SLIME_VLLM_PATCH_SITE="${SLIME_VLLM_PATCH_SITE:-0}"

export PYTHONUNBUFFERED=1
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export SLIME_SGLANG_PYTORCH_CUDA_ALLOC_CONF="${SLIME_SGLANG_PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:128}"
