#!/usr/bin/env bash

# Isolated configuration for the OpenR1-Math-220k 50k SFT + 1k/+4k OPD run.
# Source after env.sh so none of the prior OpenThoughts output paths can leak in.

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "Source this file after env.sh instead of executing it." >&2
  exit 2
fi

export OPENR1_EXPERIMENT_LABEL="${OPENR1_EXPERIMENT_LABEL:-openr1_math220k_default_sft50k_opd5120}"
export OPENR1_DATASET="${OPENR1_DATASET:-open-r1/OpenR1-Math-220k}"
export OPENR1_CONFIG="${OPENR1_CONFIG:-default}"
export OPENR1_SPLIT="${OPENR1_SPLIT:-train}"
export OPENR1_REVISION="${OPENR1_REVISION:-dc748648036c1ed619b020e056dc4b603eb39817}"
export OPENR1_DATA_DIR="${OPENR1_DATA_DIR:-${DATA_ROOT}/${OPENR1_EXPERIMENT_LABEL}}"
export OPENR1_SUCCESS_FILE="${OPENR1_SUCCESS_FILE:-${OPENR1_DATA_DIR}/_SUCCESS}"

export DATA_SEED="${DATA_SEED:-1234}"
export SFT_SIZE="${OPENR1_SFT_SIZE:-50000}"
export CLEANED_OPD_FIRST_SIZE="${OPENR1_OPD_FIRST_SIZE:-1024}"
export CLEANED_OPD_NEXT_SIZE="${OPENR1_OPD_NEXT_SIZE:-4096}"
export SFT_PARQUET="${OPENR1_DATA_DIR}/sft_050000.jsonl"
export CLEANED_OPD_RESERVE_JSONL="${OPENR1_DATA_DIR}/opd_reserve_005120.jsonl"
export CLEANED_OPD_1K_JSONL="${OPENR1_DATA_DIR}/opd_001024.jsonl"
export CLEANED_OPD_4K_JSONL="${OPENR1_DATA_DIR}/opd_next_004096.jsonl"
export SPLIT_METADATA="${OPENR1_DATA_DIR}/split_metadata.json"

export SFT_NUM_EPOCH=1
export SFT_ROLLOUT_BATCH_SIZE=250
export SFT_GLOBAL_BATCH_SIZE=250
export SFT_NUM_ROLLOUT=200
export SFT_FINAL_ROLLOUT_ID=199
export SFT_MILESTONE_ROLLOUT_IDS="19 39 59 79 99 119 139 159 179 199"
export SFT_SAVE_INTERVAL=20
export SFT_ACTOR_GPUS=4
export SFT_TENSOR_MODEL_PARALLEL_SIZE=2
export SFT_CONTEXT_PARALLEL_SIZE=1
export SFT_PIPELINE_MODEL_PARALLEL_SIZE=1
export SFT_OPTIMIZER_MODE=megatron_distributed_optimizer
export SFT_ZERO_STAGE=1
export SFT_CKPT_FORMAT=torch_dist
export SFT_LOSS_MASK_TYPE=qwen3
export SFT_LOSS_MASK_PREFLIGHT_ENABLED=1
export SFT_LOSS_MASK_PREFLIGHT_REQUIRE_THINK=1
export SFT_LOSS_MASK_PREFLIGHT_SAMPLES=3
export SFT_MAX_TOKENS_PER_GPU=12288
export SFT_LOG_PROBS_CHUNK_SIZE=4096
export SFT_OPTIMIZER_CPU_OFFLOAD=1
export SFT_RECOMPUTE_LOSS_FUNCTION=1
export SFT_LR=1e-6

export SFT_SAVE_DIR="${OUTPUT_ROOT}/qwen3_8b_${OPENR1_EXPERIMENT_LABEL}_sft_full_optim"
export SFT_HF_SNAPSHOT_DIR="${OUTPUT_ROOT}/qwen3_8b_${OPENR1_EXPERIMENT_LABEL}_sft_eval_snapshots"
export SFT_DETAILS_DIR="${OUTPUT_ROOT}/${OPENR1_EXPERIMENT_LABEL}_sft_details"
export SFT_HF_SNAPSHOT_TEMPLATE="${SFT_HF_SNAPSHOT_DIR}/iter_{rollout_id:07d}"
export SFT_FINAL_HF_DIR="${SFT_HF_SNAPSHOT_DIR}/iter_0000199"
export SFT_FINAL_FULL_CKPT_DIR="${SFT_SAVE_DIR}/iter_0000199"

export BASE_EVAL_OUTPUT_DIR="${OUTPUT_ROOT}/math500_eval_cleaned_base_vllm"
export SFT_EVAL_OUTPUT_DIR="${OUTPUT_ROOT}/math500_eval_${OPENR1_EXPERIMENT_LABEL}_sft_vllm"
export OPD_EVAL_OUTPUT_DIR="${OUTPUT_ROOT}/math500_eval_${OPENR1_EXPERIMENT_LABEL}_opd_vllm"
export COMBINED_EVAL_OUTPUT_DIR="${OUTPUT_ROOT}/math500_eval_${OPENR1_EXPERIMENT_LABEL}_combined"
export CHECKPOINT_REPORT_DIR="${OUTPUT_ROOT}/checkpoint_reports_${OPENR1_EXPERIMENT_LABEL}"

export OPD_ACTOR_GPUS=3
export OPD_ROLLOUT_GPUS=3
export OPD_RAY_GPUS=3
export OPD_TEACHER_GPU=3
export OPD_TENSOR_MODEL_PARALLEL_SIZE=1
export OPD_CONTEXT_PARALLEL_SIZE=3
export OPD_SEQ_LENGTH=32766
export OPD_ROLLOUT_MAX_CONTEXT_LEN=32766
export OPD_MAX_RESPONSE_LEN=31744
export OPD_MAX_TOKENS_PER_GPU=2048
export OPD_LOG_PROBS_CHUNK_SIZE=512
export OPD_TRAIN_MEMORY_MARGIN_BYTES=0
export OPD_LR=1e-6
export OPD_COLOCATE=1
export OPD_OFFLOAD_TRAIN=1
export OPD_OFFLOAD_ROLLOUT=1
export OPD_OPTIMIZER_CPU_OFFLOAD=1
export OPD_RECOMPUTE_LOSS_FUNCTION=1
export OPD_SANITY_FAIL_ON_COLLAPSE=0

export OPENR1_OPD1_RUN_LABEL="${OPENR1_EXPERIMENT_LABEL}_opd1k"
export OPENR1_OPD_CONT_RUN_LABEL="${OPENR1_EXPERIMENT_LABEL}_opd_continue"
export OPENR1_OPD1_SAVE_DIR="${OUTPUT_ROOT}/qwen3_8b_${OPENR1_EXPERIMENT_LABEL}_opd1k_full_optim"
export OPENR1_OPD1_HF_SNAPSHOT_DIR="${OUTPUT_ROOT}/qwen3_8b_${OPENR1_EXPERIMENT_LABEL}_opd1k_eval_snapshots"
export OPENR1_OPD1_ROLLOUT_LOG_DIR="${OUTPUT_ROOT}/${OPENR1_OPD1_RUN_LABEL}_rollout_logs"
export OPENR1_OPD1_SANITY_DIR="${OUTPUT_ROOT}/${OPENR1_OPD1_RUN_LABEL}_sanity"
export OPENR1_OPD_CONT_SAVE_DIR="${OUTPUT_ROOT}/qwen3_8b_${OPENR1_EXPERIMENT_LABEL}_opd_continue_full_optim"
export OPENR1_OPD_CONT_HF_SNAPSHOT_DIR="${OUTPUT_ROOT}/qwen3_8b_${OPENR1_EXPERIMENT_LABEL}_opd_continue_eval_snapshots"
export OPENR1_OPD_CONT_ROLLOUT_LOG_DIR="${OUTPUT_ROOT}/${OPENR1_OPD_CONT_RUN_LABEL}_rollout_logs"
export OPENR1_OPD_CONT_SANITY_DIR="${OUTPUT_ROOT}/${OPENR1_OPD_CONT_RUN_LABEL}_sanity"

export EVAL_BACKEND=vllm
export EVAL_MAX_RESPONSE_LEN=31744
export EVAL_MAX_CONTEXT_LEN=32768
export EVAL_EXPECTED_SAMPLES=500
export VLLM_EVAL_NUM_GPUS=4
export VLLM_EVAL_MAX_MODEL_LEN=32768
export VLLM_EVAL_GPU_MEMORY_UTILIZATION=0.92
export VLLM_EVAL_MAX_NUM_SEQS=8
export VLLM_EVAL_MAX_NUM_BATCHED_TOKENS=16384
export VLLM_EVAL_KV_CACHE_DTYPE=auto
export VLLM_EVAL_ENABLE_PREFIX_CACHING=1
export VLLM_EVAL_ENABLE_CHUNKED_PREFILL=1
export VLLM_EVAL_ASYNC_SCHEDULING=0
export VLLM_EVAL_SAFETENSORS_LOAD_STRATEGY=prefetch
export VLLM_EVAL_SPECULATIVE_METHOD=none
export VLLM_EVAL_NUM_SPECULATIVE_TOKENS=0
export VLLM_EVAL_PROMPT_LOOKUP_MIN=5
export VLLM_EVAL_PROMPT_LOOKUP_MAX=5
export VLLM_EVAL_CHUNK_SIZE=16
export VLLM_EVAL_RESUME_COMPLETED=1
export VLLM_EVAL_PRESERVE_SPECIAL_TOKENS=1

export REPORT_INCLUDE_SFT=1
export REPORT_SFT_FINAL_ONLY=1
export REPORT_OPD_FINAL_ONLY=0
export REPORT_OPD_X_OFFSET_SAMPLES=50000
export REPORT_OPD_LABEL_PREFIX="SFT+"
export REPORT_EXPERIMENT_NOTE="${REPORT_EXPERIMENT_NOTE:-OpenR1-Math-220k default reproduction: Qwen3-8B-Base -> 50k SFT -> 1,024 OPD -> 5,120 cumulative OPD.}"
