#!/usr/bin/env bash

# Static paths/config shared by strict-English prep, dispatch, and child jobs.
export STRICT_EN_EXPERIMENT_LABEL="${STRICT_EN_EXPERIMENT_LABEL:-strict_en_v2_math45k_opd5k}"
export CLEANED_EXPERIMENT_LABEL="${STRICT_EN_EXPERIMENT_LABEL}"
export CLEANED_OUTPUT_TAG="${STRICT_EN_EXPERIMENT_LABEL}"
export STRICT_EN_DATASET_DIR="${STRICT_EN_DATASET_DIR:-${DATA_ROOT}/openthoughts3_${STRICT_EN_EXPERIMENT_LABEL}}"
# env.sh defines paths for the older cleaned experiment. Use strict-specific
# override names so sourcing order can never redirect this run into old paths.
export SFT_PARQUET="${STRICT_EN_SFT_JSONL:-${STRICT_EN_DATASET_DIR}/strict_math_sft.jsonl}"
export CLEANED_OPD_RESERVE_JSONL="${STRICT_EN_OPD_RESERVE_JSONL:-${STRICT_EN_DATASET_DIR}/strict_math_opd_reserve.jsonl}"
export CLEANED_OPD_1K_JSONL="${STRICT_EN_OPD_1K_JSONL:-${STRICT_EN_DATASET_DIR}/strict_math_opd_001024.jsonl}"
export CLEANED_OPD_4K_JSONL="${STRICT_EN_OPD_CONTINUATION_JSONL:-${STRICT_EN_DATASET_DIR}/strict_math_opd_continuation.jsonl}"
export CLEANED_METADATA="${STRICT_EN_METADATA:-${STRICT_EN_DATASET_DIR}/split_metadata.json}"
export SPLIT_METADATA="${CLEANED_METADATA}"

export STRICT_MATH_MAX_SELECTED="${STRICT_MATH_MAX_SELECTED:-50000}"
export STRICT_OPD_RESERVE_SIZE="${STRICT_OPD_RESERVE_SIZE:-5000}"
export CLEANED_OPD_FIRST_SIZE="${CLEANED_OPD_FIRST_SIZE:-1024}"
export SFT_ROLLOUT_BATCH_SIZE="${SFT_ROLLOUT_BATCH_SIZE:-250}"
export SFT_GLOBAL_BATCH_SIZE="${SFT_GLOBAL_BATCH_SIZE:-250}"
export OPD_ROLLOUT_BATCH_SIZE="${OPD_ROLLOUT_BATCH_SIZE:-128}"
export OPD_GLOBAL_BATCH_SIZE="${OPD_GLOBAL_BATCH_SIZE:-128}"

export SFT_ACTOR_GPUS="${SFT_ACTOR_GPUS:-4}"
export SFT_TENSOR_MODEL_PARALLEL_SIZE="${SFT_TENSOR_MODEL_PARALLEL_SIZE:-2}"
export SFT_CONTEXT_PARALLEL_SIZE="${SFT_CONTEXT_PARALLEL_SIZE:-1}"
export SFT_PIPELINE_MODEL_PARALLEL_SIZE="${SFT_PIPELINE_MODEL_PARALLEL_SIZE:-1}"
export SFT_OPTIMIZER_MODE="${SFT_OPTIMIZER_MODE:-megatron_distributed_optimizer}"
export SFT_ZERO_STAGE="${SFT_ZERO_STAGE:-1}"
export SFT_CKPT_FORMAT="${SFT_CKPT_FORMAT:-torch_dist}"
export SFT_LOSS_MASK_TYPE="${SFT_LOSS_MASK_TYPE:-qwen3}"
export SFT_LOSS_MASK_PREFLIGHT_ENABLED="${SFT_LOSS_MASK_PREFLIGHT_ENABLED:-1}"
export SFT_LOSS_MASK_PREFLIGHT_REQUIRE_THINK="${SFT_LOSS_MASK_PREFLIGHT_REQUIRE_THINK:-1}"
export SFT_MAX_TOKENS_PER_GPU="${SFT_MAX_TOKENS_PER_GPU:-16384}"
export SFT_NUM_EPOCH="${SFT_NUM_EPOCH:-1}"
export SFT_LR="${SFT_LR:-1e-6}"

export OPD_ACTOR_GPUS="${OPD_ACTOR_GPUS:-3}"
export OPD_ROLLOUT_GPUS="${OPD_ROLLOUT_GPUS:-3}"
export OPD_RAY_GPUS="${OPD_RAY_GPUS:-3}"
export OPD_TEACHER_GPU="${OPD_TEACHER_GPU:-3}"
export OPD_TENSOR_MODEL_PARALLEL_SIZE="${OPD_TENSOR_MODEL_PARALLEL_SIZE:-1}"
export OPD_CONTEXT_PARALLEL_SIZE="${OPD_CONTEXT_PARALLEL_SIZE:-3}"
export OPD_SEQ_LENGTH="${OPD_SEQ_LENGTH:-32766}"
export OPD_ROLLOUT_MAX_CONTEXT_LEN="${OPD_ROLLOUT_MAX_CONTEXT_LEN:-32766}"
export OPD_MAX_RESPONSE_LEN="${OPD_MAX_RESPONSE_LEN:-31744}"
export OPD_MAX_TOKENS_PER_GPU="${OPD_MAX_TOKENS_PER_GPU:-2048}"
export OPD_LOG_PROBS_CHUNK_SIZE="${OPD_LOG_PROBS_CHUNK_SIZE:-512}"
export OPD_TRAIN_MEMORY_MARGIN_BYTES="${OPD_TRAIN_MEMORY_MARGIN_BYTES:-0}"
export OPD_LR="${OPD_LR:-1e-6}"
export OPD_COLOCATE="${OPD_COLOCATE:-1}"
export OPD_OFFLOAD_TRAIN="${OPD_OFFLOAD_TRAIN:-1}"
export OPD_OFFLOAD_ROLLOUT="${OPD_OFFLOAD_ROLLOUT:-1}"
export OPD_OPTIMIZER_CPU_OFFLOAD="${OPD_OPTIMIZER_CPU_OFFLOAD:-1}"
export OPD_RECOMPUTE_LOSS_FUNCTION="${OPD_RECOMPUTE_LOSS_FUNCTION:-1}"
export OPD_SANITY_FAIL_ON_COLLAPSE="${OPD_SANITY_FAIL_ON_COLLAPSE:-0}"

export QWEN3_ENABLE_THINKING=1
export QWEN3_STOP_TOKEN_IDS="151645 151643"
export OPD_ROLLOUT_STOP_TOKEN_IDS="151645 151643"
export EVAL_STOP_TOKEN_IDS="151645 151643"
export EVAL_BACKEND=vllm
export EVAL_MAX_RESPONSE_LEN=31744
export EVAL_MAX_CONTEXT_LEN=32768
export EVAL_EXPECTED_SAMPLES=500
export VLLM_EVAL_NUM_GPUS=4
export VLLM_EVAL_GPU_MEMORY_UTILIZATION=0.97
export VLLM_EVAL_MAX_NUM_SEQS=24
export VLLM_EVAL_MAX_NUM_BATCHED_TOKENS=16384
export VLLM_EVAL_KV_CACHE_DTYPE=auto
export VLLM_EVAL_ENABLE_PREFIX_CACHING=0
export VLLM_EVAL_ENABLE_CHUNKED_PREFILL=1
export VLLM_EVAL_ASYNC_SCHEDULING=1
export VLLM_EVAL_SAFETENSORS_LOAD_STRATEGY=prefetch
export VLLM_EVAL_SPECULATIVE_METHOD=none
export VLLM_EVAL_NUM_SPECULATIVE_TOKENS=0
export VLLM_EVAL_PROMPT_LOOKUP_MIN=5
export VLLM_EVAL_PROMPT_LOOKUP_MAX=5
export VLLM_EVAL_CHUNK_SIZE=16
export VLLM_EVAL_RESUME_COMPLETED=1
export VLLM_EVAL_PRESERVE_SPECIAL_TOKENS=1

export BASE_EVAL_OUTPUT_DIR="${BASE_EVAL_OUTPUT_DIR:-${OUTPUT_ROOT}/math500_eval_cleaned_base_vllm}"
export REPORT_INCLUDE_SFT=1
export REPORT_SFT_FINAL_ONLY=1
export REPORT_OPD_FINAL_ONLY=0
export REPORT_EXPERIMENT_NOTE="Strict-English v2 OpenThoughts: base -> SFT -> OPD-1k -> OPD-final"
