#!/usr/bin/env bash

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "Source this file instead of executing it." >&2
  exit 2
fi

export FULL_REPRO_DIR
FULL_REPRO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
export SLIME_REPO_ROOT
SLIME_REPO_ROOT="$(cd -- "${FULL_REPRO_DIR}/../.." >/dev/null 2>&1 && pwd)"

export CONTRACT_FILE="${FULL_REPRO_DIR}/config/experiment_contract.json"
export CONTRACT_HASH
CONTRACT_HASH="$(sha256sum "${CONTRACT_FILE}" | awk '{print substr($1,1,16)}')"
export EXPERIMENT_ROOT="/gpfs/scrubbed/suryadv/slime-qwen3-8b-32b-full-repro/v1/${CONTRACT_HASH}"
export SCRATCH_ROOT="${EXPERIMENT_ROOT}"
export DATA_ROOT="${EXPERIMENT_ROOT}/data"
export OUTPUT_ROOT="${EXPERIMENT_ROOT}/outputs"
export SLURM_LOG_DIR="${EXPERIMENT_ROOT}/slurm_logs"
export MANIFEST_ROOT="${EXPERIMENT_ROOT}/manifests"
export TMPDIR="${TMPDIR:-${EXPERIMENT_ROOT}/tmp}"
export RAY_TMPDIR="${RAY_TMPDIR:-${EXPERIMENT_ROOT}/ray_tmp}"
export WANDB_DIR="${EXPERIMENT_ROOT}/wandb"
export WANDB_MODE="${WANDB_MODE:-offline}"

# Reuse immutable, already-cached source artifacts. New outputs never enter the
# earlier experiment tree.
export LEGACY_CACHE_ROOT="/gpfs/scrubbed/suryadv/slime-qwen3-8b-opd"
export MODEL_ROOT="${LEGACY_CACHE_ROOT}/models"
export HF_HOME="${LEGACY_CACHE_ROOT}/hf_home"
export HF_DATASETS_CACHE="${HF_HOME}/datasets"
export TRANSFORMERS_CACHE="${HF_HOME}/transformers"
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export SLIME_SIF="${LEGACY_CACHE_ROOT}/containers/slime_latest.sandbox"
export VLLM_EVAL_SITE="${LEGACY_CACHE_ROOT}/vllm_eval_site"
export MATH_VERIFY_SITE="/gpfs/scrubbed/suryadv/slime-qwen3-4b-opd-harp-v2/harp_eval_site"
export EVAL_ZIG_CC="${EVAL_ZIG_CC:-${MATH_VERIFY_SITE}/bin/zig-cc}"
export EVAL_ZIG_INCLUDE_ROOT="${EVAL_ZIG_INCLUDE_ROOT:-${MATH_VERIFY_SITE}/python_include}"
export SFT_TORCH_COMPILE_CC="${SFT_TORCH_COMPILE_CC:-${EVAL_ZIG_CC}}"
export SFT_TORCH_COMPILE_CPATH="${SFT_TORCH_COMPILE_CPATH:-${EVAL_ZIG_INCLUDE_ROOT}/python3.12:${EVAL_ZIG_INCLUDE_ROOT}}"

export STUDENT_HF_REPO="Qwen/Qwen3-8B-Base"
export STUDENT_HF_REVISION="49e3418fbbbca6ecbdf9608b4d22e5a407081db4"
export TEACHER_HF_REPO="Qwen/Qwen3-32B"
export TEACHER_HF_REVISION="9216db5781bf21249d130ec9da846c4624c16137"
export STUDENT_HF_DIR="${MODEL_ROOT}/Qwen3-8B-Base"
export TEACHER_HF_DIR="${MODEL_ROOT}/Qwen3-32B"
export STUDENT_TORCH_DIST_DIR="${MODEL_ROOT}/Qwen3-8B-Base_torch_dist"
export OT3_DATASET="open-thoughts/OpenThoughts3-1.2M"
export OT3_REVISION="61bcf9d4eb38b30295efc2021227a63cc5bb34c8"
export OT3_SPLIT="train"
export MATH500_DATASET="HuggingFaceH4/MATH-500"
export MATH500_REVISION="6e4ed1a2a79af7d8630a6b768ec859cb5af4d3be"

export DATA_SEED=1234
export SFT_SIZE=200000
export OPD_POOL_SIZE=100000
export OPD_TRAIN_SIZE=1472
export SFT_PARQUET="${DATA_ROOT}/openthoughts3_sft_200000.jsonl"
export CLEANED_OPD_RESERVE_JSONL="${DATA_ROOT}/openthoughts3_opd_reserve_100000.jsonl"
export OPD_JSONL="${DATA_ROOT}/openthoughts3_opd_headline_001472.jsonl"
export SPLIT_METADATA="${DATA_ROOT}/cleanup_and_split_audit.json"
export CLEANUP_AUDIT_JSON="${DATA_ROOT}/cleanup_audit.json"
export CLEANUP_AUDIT_MD="${DATA_ROOT}/cleanup_audit.md"
export CLEANUP_WORK_DIR="${DATA_ROOT}/cleanup_work"

export SFT_SAVE_DIR="${OUTPUT_ROOT}/sft_full_state"
export SFT_HF_SNAPSHOT_DIR="${OUTPUT_ROOT}/sft_weights"
export SFT_DETAILS_DIR="${OUTPUT_ROOT}/sft_details"
export SFT_FINAL_HF_DIR="${SFT_HF_SNAPSHOT_DIR}/iter_0000999"
export SFT_FINAL_FULL_CKPT_DIR="${SFT_SAVE_DIR}/iter_0000999"
export SFT_HF_SNAPSHOT_TEMPLATE="${SFT_HF_SNAPSHOT_DIR}/iter_{rollout_id:07d}"
export CHECKPOINT_REPORT_DIR="${OUTPUT_ROOT}/checkpoint_reports"

export SFT_NUM_EPOCH=1
export SFT_ROLLOUT_BATCH_SIZE=200
export SFT_GLOBAL_BATCH_SIZE=200
export SFT_NUM_ROLLOUT=1000
export SFT_FINAL_ROLLOUT_ID=999
export SFT_MILESTONE_ROLLOUT_IDS="124 249 374 499 624 749 874 999"
export SFT_SAVE_INTERVAL=125
export SFT_ACTOR_GPUS=4
export SFT_TENSOR_MODEL_PARALLEL_SIZE=2
export SFT_CONTEXT_PARALLEL_SIZE=1
export SFT_PIPELINE_MODEL_PARALLEL_SIZE=1
export SFT_ZERO_STAGE=1
export SFT_CKPT_FORMAT=torch_dist
export SFT_LOSS_MASK_TYPE=qwen3
export SFT_LOSS_MASK_PREFLIGHT_ENABLED=1
export SFT_LOSS_MASK_PREFLIGHT_REQUIRE_THINK=1
export SFT_LOSS_MASK_PREFLIGHT_SAMPLES=8
export SFT_MAX_TOKENS_PER_GPU=16384
export SFT_SEQ_LENGTH=32768
export SFT_GRAD_CLIP=1.0
export SFT_LOG_PROBS_CHUNK_SIZE=-1
export SFT_OPTIMIZER_CPU_OFFLOAD=1
export SFT_RECOMPUTE_LOSS_FUNCTION=1
export SFT_LR=1e-6

export OPD_RUN_LABEL=full200k_ot3_001472_r16k_colocate4
export OPD_SAVE_DIR="${OUTPUT_ROOT}/opd_full_state"
export OPD_HF_SNAPSHOT_DIR="${OUTPUT_ROOT}/opd_weights"
export OPD_HF_SNAPSHOT_TEMPLATE="${OPD_HF_SNAPSHOT_DIR}/iter_{rollout_id:07d}"
export OPD_FINAL_HF_DIR="${OPD_HF_SNAPSHOT_DIR}/iter_0000091"
export OPD_ROLLOUT_LOG_DIR="${OUTPUT_ROOT}/opd_rollouts"
export OPD_SANITY_REPORT_DIR="${OUTPUT_ROOT}/opd_sanity"
export OPD_SANITY_SUMMARY_DIR="${OPD_SANITY_REPORT_DIR}"
export OPD_ROLLOUT_AUDIT_JSONL="${OPD_SANITY_REPORT_DIR}/rollout_trajectory_audit.jsonl"
export OPD_ROLLOUT_AUDIT_JSON="${OPD_SANITY_REPORT_DIR}/rollout_audit.json"
export OPD_ROLLOUT_AUDIT_MD="${OPD_SANITY_REPORT_DIR}/rollout_audit.md"
export TEACHER_LOG_DIR="${OUTPUT_ROOT}/teacher_logs"
export OPD_TRAINED_MANIFEST="${OPD_SAVE_DIR}/opd_trained_manifest.json"
export OPD_INITIAL_LOAD_MODE=hf
export OPD_INITIAL_LOAD_DIR="${SFT_FINAL_HF_DIR}"
export OPD_REF_LOAD_DIR="${SFT_FINAL_HF_DIR}"
export OPD_ROLLOUT_BATCH_SIZE=16
export OPD_GLOBAL_BATCH_SIZE=64
export OPD_N_SAMPLES_PER_PROMPT=4
export OPD_NUM_ROLLOUT=92
export OPD_FINAL_ROLLOUT_ID=91
export OPD_EFFECTIVE_TRAIN_SAMPLES=1472
export OPD_MILESTONE_ROLLOUT_IDS="22 45 68 91"
export OPD_SAVE_INTERVAL=23
export OPD_MAX_RESPONSE_LEN=16384
export OPD_SEQ_LENGTH=16380
export OPD_ROLLOUT_MAX_CONTEXT_LEN=16380
export OPD_ROLLOUT_TEMPERATURE=0.8
export OPD_ROLLOUT_TOP_P=1.0
export OPD_ROLLOUT_TOP_K=-1
export OPD_MAX_TOKENS_PER_GPU=4096
export OPD_LOG_PROBS_CHUNK_SIZE=1024
export OPD_TRAIN_MEMORY_MARGIN_BYTES=0
export OPD_LR=1e-6
export OPD_ACTOR_GPUS=3
export OPD_ROLLOUT_GPUS=3
export OPD_RAY_GPUS=3
export OPD_TEACHER_GPU=3
export OPD_TENSOR_MODEL_PARALLEL_SIZE=1
export OPD_CONTEXT_PARALLEL_SIZE=3
export OPD_COLOCATE=1
export OPD_OFFLOAD_TRAIN=1
export OPD_OFFLOAD_ROLLOUT=1
export OPD_OPTIMIZER_CPU_OFFLOAD=1
export OPD_RECOMPUTE_LOSS_FUNCTION=1
export OPD_DISABLE_CUDA_GRAPH=1
export OPD_TEACHER_MEM_FRACTION=0.65
export OPD_TEACHER_CHUNKED_PREFILL_SIZE=8192
export OPD_TEACHER_MAX_PREFILL_TOKENS=16384
export OPD_SANITY_CHECK_ENABLED=1
export OPD_SANITY_FAIL_ON_COLLAPSE=0
export OPD_SANITY_MAX_CAP_HIT_RATE=0.15
export OPD_SANITY_MAX_AVG_RESPONSE_TOKENS=16384
export OPD_SANITY_MIN_FINAL_ANSWER_RATE=0.85
export OPD_ALLOW_OPT_PARAM_SCHEDULER_MISMATCH=0
export OPD_SKIP_ROLLOUT_DATA_STATE_LOAD=0
export OPD_ALREADY_TRAINED_SAMPLES=0
export OPD_START_ROLLOUT_ID=0
export OPD_MANIFEST_FROM_ROLLOUT_LOGS=0
export OPD_RETIRE_PREVIOUS_FULL_SAVE_DIR=""
export OPD_RETIRE_PREVIOUS_HF_DIR=""

export QWEN3_ENABLE_THINKING=1
export QWEN3_IM_END_TOKEN_ID=151645
export QWEN3_ENDOFTEXT_TOKEN_ID=151643
export QWEN3_STOP_TOKEN_IDS="151645 151643"
export OPD_ROLLOUT_STOP_TOKEN_IDS="${QWEN3_STOP_TOKEN_IDS}"
export EVAL_STOP_TOKEN_IDS="${QWEN3_STOP_TOKEN_IDS}"
export EVAL_TEMPERATURE=0.8
export EVAL_TOP_P=0.7
export EVAL_TOP_K=-1
export EVAL_NUM_REPEATS=1
export EVAL_MAX_RESPONSE_LEN=16384
export EVAL_SAFETY_MARGIN=64
export EVAL_SEED=1234
export EVAL_OUTPUT_ROOT="${OUTPUT_ROOT}/math500"
export EVAL_EXPECTED_SAMPLES=500
export EVAL_PROMPT='Please reason step by step, and put your final answer within \boxed{}.'

export CHECKPOINT_PRUNE_INTERVAL_SECONDS=60
export ESTIMATED_FULL_OPTIM_CKPT_BYTES=115000000000
export ACCOUNT="${ACCOUNT:-raivn}"
export PARTITION="${PARTITION:-gpu-h200}"
export QOS="${QOS:-normal}"
export GPU_GRES=gpu:h200:4
export PYTHONUNBUFFERED=1
export TOKENIZERS_PARALLELISM=false
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export SLIME_SGLANG_PYTORCH_CUDA_ALLOC_CONF="${SLIME_SGLANG_PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:128}"
export SLIME_SGLANG_FORCE_NATIVE_ROPE="${SLIME_SGLANG_FORCE_NATIVE_ROPE:-1}"
export SLIME_SGLANG_PATCH_SITE="${SLIME_SGLANG_PATCH_SITE:-1}"
